version: "3.9"

services:
  dias-sin-accidentes-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dias-sin-accidentes:dev
    container_name: dias-sin-accidentes-dev
    restart: unless-stopped
    ports:
      - "3001:4443"
    environment:
      NODE_ENV: development
      PORT: 4443
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-dev}
      DATA_FILE_PATH: /data/data.test.json
      TZ: America/Santiago
    volumes:
      - ../data:/data:rw
      - ../logs:/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:4443/api/counter", "--insecure"]
      interval: 1m
      timeout: 10s
      retries: 3
    command: ["node", "src/server.js"]

